name: Sync master to laptop
on:
  push:
    branches: [ "master" ]
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge master -> laptop
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: master
          target_branch: laptop
          github_token: ${{ secrets.GITHUB_TOKEN }}
